name: Move HTML files to public directory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  move-html-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create public directory if not exists
      run: mkdir -p public

    - name: Move HTML files to public directory
      run: |
        find . -maxdepth 1 -name "*.html" -exec mv {} public/ \;

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Move HTML files to public directory"
        git push https://x-access-token:${{ secrets.ACTIONS_SECRET_PAT }}@github.com/cdxiaodong/SingleFile-Archives.git
